version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: pgvector_container
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "127.0.0.1:5433:5432"  
    volumes:
      - pgvector_data:/var/lib/postgresql/data
      - ./database/sql_scripts/init-unaccent.sql:/docker-entrypoint-initdb.d/init-unaccent.sql:ro

volumes:
  pgvector_data:


